services:
  postgis:
    image: postgis/postgis:latest
    container_name: postgis_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: gisdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: my_app
    depends_on:
      - postgis
    environment:
      DATABASE_URL: postgresql://admin:admin@postgis:5432/gisdb
    ports:
      - "8000:8000"
    command: >
      sh -c "
        uv run python scripts/create_schema.py &&
        uv run python scripts/poi_download.py &&
        uv run fastapi run app.py --port 80 --host 0.0.0.0
      "

volumes:
  db_data: